### PR TITLE
Fe/lab5/CI

### PR DESCRIPTION
**Pull request by KirylAkulich1**
Simple firebase CI implemented 
SITE : https://jsaliasgame.firebaseapp.com/

### CODE REVIEW

**Comment by KirylAkulich1** [comment]
All requested features were implemented in Lab4

**Comment by gmltA** [comment]
>Word set management (CRUD)
Word set selection (with example words from the set)

I was't able to find these features.

**Review by gmltA — APPROVED** [review]
Okay. It's a <kbd>9</kbd>. And the resulting arm will be <kbd>7</kbd>

**Comment by KirylAkulich1** [comment]
Thank you

**Pull request merged**
